### PR TITLE
Added 2 papers

### PR DESCRIPTION
**Pull request by tdiethe**
Both Amazon papers from the NeurIPS 2018 Continual Learning workshop

### CODE REVIEW

**Comment by TLESORT** [comment]
Hi, thanks for your contribution :)
The md file is generated automatically from the bibtex file by running in the main directory:
```
python scripts/bibtex_to_md.py 
```
Therefore you should modify only the bibtexfile and generate md file with the script and not manually (I will make the process clear in the main readme).
If you wish to add the paper to a specific category, you should add some keywords in the bib entry.
You should probably also add the url manually in the bib entry.
I hope I explained it clearly, I will make a readme file in the script repo to explain :)
Chears
Timothée

**Comment by TLESORT** [comment]
I have put the process here:
https://github.com/optimass/continual_learning_papers/blob/master/scripts/README.md

**Comment by tdiethe** [comment]
Ah sorry will fix

**Comment by tdiethe** [comment]
I got the error "Entry type software not standard. Not considered." for one
of the entries already there - did you do anything special to run the
script?

**Comment by tdiethe** [comment]
Ok should all be fixed now. I note that the entry on line 1237: https://github.com/tdiethe/continual_learning_papers/blob/96431313853b600ad6115dfe0620969f0d642b9e/bibtex.bib#L1237
still doesn't appear - not sure if this is due to the parser dropping unknown bib types or because it's not categorized?

**Comment by TLESORT** [comment]
Thanks a lot for fixing Ruvolo13 and Lesort19Data Entries!
I had previously the message "Entry type software not standard. Not considered." but I thought it was not breaking anything :)

**Pull request merged**
