### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by ffeng1996**
Add one new paper: A Wholistic View of Continual Learning with Deep Neural Networks: Forgotten Lessons and the Bridge to Active and Open World Learning

### CODE REVIEW

**Comment by TLESORT** [comment]
Hi ffeng1996, 

thanks for your contribution!  Maybe you can merge you two PR into just one ;)
Moreover I think the modif in the README.md has not been generated as explained in https://github.com/optimass/continual_learning_papers/blob/master/scripts/README.md
(the comment is not in the bibtex)
Moreover, it could be nice if the comment explains the paper a little bit more or differently than the tittle :)

If you need help, do not mind to ask
Timothée

**Comment by TLESORT** [comment]
I just update the contribu

**Comment by TLESORT** [comment]
Sorry missclick

**Comment by ffeng1996** [comment]
Thanks, Timothée.

I will re-open an issue about two changes and add some descriptions of this paper.

**Pull request closed without merging**
